/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

public class LinkedList<T> {
    public Node<T> head = null;

    public void insert(T value) {
        Node node = new Node(value);
        if (this.head != null)
            node.next = this.head;
        this.head = node;
    }

    public boolean includes(T value) {
        Node<T> current = this.head;
        while (current != null) {
            if (current.value == value) {
                return true;
            }
            current = current.next;
        }
        return false;
    }

    public String toString() {
        StringBuilder sb = new StringBuilder();
        Node<T> current = this.head;
        while (current != null) {
            sb.append("{");
            sb.append(current.value);
            sb.append("} -> ");
            current = current.next;
        }
        sb.append("null");
        return sb.toString();
    }
}
